// <auto-generated />
namespace Project_Maverick.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EidtContractPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EidtContractPost));
        
        string IMigrationMetadata.Id
        {
            get { return "201609201547445_Eidt-ContractPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
